name: ML Pipeline

on:
  workflow_dispatch:
    inputs:
      learning_rate:
        description: 'Learning rate'
        required: true
        default: '0.001'
      epochs:
        description: 'Number of training epochs'
        required: true
        default: '50'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py --learning_rate ${{ github.event.inputs.learning_rate }} --epochs ${{ github.event.inputs.epochs }}

      - name: Upload model and test data
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: |
            data/cardio_model_tf.h5
            data/test_data.csv

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download model and test data
        uses: actions/download-artifact@v4
        with:
          name: model
          path: data

      - name: Evaluate model
        run: |
          python evaluate.py

      - name: Upload evaluation results
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: |
            data/predictions.csv
            data/metrics.csv
            data/plot.png
